/** UN member (+ observers) country list for join country picker. */
export type CountryCode = string;

export type Country = {
  code: string;
  en: string;
  de: string;
};

export const COUNTRIES: Country[] = [
  { code: 'AD', en: 'Andorra', de: 'Andorra' },
  { code: 'AE', en: 'United Arab Emirates', de: 'Vereinigte Arabische Emirate' },
  { code: 'AF', en: 'Afghanistan', de: 'Afghanistan' },
  { code: 'AG', en: 'Antigua and Barbuda', de: 'Antigua und Barbuda' },
  { code: 'AL', en: 'Albania', de: 'Albanien' },
  { code: 'AM', en: 'Armenia', de: 'Armenien' },
  { code: 'AO', en: 'Angola', de: 'Angola' },
  { code: 'AR', en: 'Argentina', de: 'Argentinien' },
  { code: 'AT', en: 'Austria', de: 'Österreich' },
  { code: 'AU', en: 'Australia', de: 'Australien' },
  { code: 'AZ', en: 'Azerbaijan', de: 'Aserbaidschan' },
  { code: 'BA', en: 'Bosnia and Herzegovina', de: 'Bosnien und Herzegowina' },
  { code: 'BB', en: 'Barbados', de: 'Barbados' },
  { code: 'BD', en: 'Bangladesh', de: 'Bangladesch' },
  { code: 'BE', en: 'Belgium', de: 'Belgien' },
  { code: 'BF', en: 'Burkina Faso', de: 'Burkina Faso' },
  { code: 'BG', en: 'Bulgaria', de: 'Bulgarien' },
  { code: 'BH', en: 'Bahrain', de: 'Bahrain' },
  { code: 'BI', en: 'Burundi', de: 'Burundi' },
  { code: 'BJ', en: 'Benin', de: 'Benin' },
  { code: 'BN', en: 'Brunei Darussalam', de: 'Brunei' },
  { code: 'BO', en: 'Bolivia, Plurinational State of', de: 'Bolivien' },
  { code: 'BR', en: 'Brazil', de: 'Brasilien' },
  { code: 'BS', en: 'Bahamas', de: 'Bahamas' },
  { code: 'BT', en: 'Bhutan', de: 'Bhutan' },
  { code: 'BW', en: 'Botswana', de: 'Botswana' },
  { code: 'BY', en: 'Belarus', de: 'Belarus' },
  { code: 'BZ', en: 'Belize', de: 'Belize' },
  { code: 'CA', en: 'Canada', de: 'Kanada' },
  { code: 'CD', en: 'Congo, Democratic Republic of the', de: 'Kongo, Demokratische Republik' },
  { code: 'CF', en: 'Central African Republic', de: 'Zentralafrikanische Republik' },
  { code: 'CG', en: 'Congo', de: 'Kongo, Republik' },
  { code: 'CH', en: 'Switzerland', de: 'Schweiz' },
  { code: 'CI', en: 'Côte d\'Ivoire', de: 'Elfenbeinküste' },
  { code: 'CL', en: 'Chile', de: 'Chile' },
  { code: 'CM', en: 'Cameroon', de: 'Kamerun' },
  { code: 'CN', en: 'China', de: 'China, Volksrepublik' },
  { code: 'CO', en: 'Colombia', de: 'Kolumbien' },
  { code: 'CR', en: 'Costa Rica', de: 'Costa Rica' },
  { code: 'CU', en: 'Cuba', de: 'Kuba' },
  { code: 'CV', en: 'Cabo Verde', de: 'Kap Verde' },
  { code: 'CY', en: 'Cyprus', de: 'Zypern' },
  { code: 'CZ', en: 'Czechia', de: 'Tschechien' },
  { code: 'DE', en: 'Germany', de: 'Deutschland' },
  { code: 'DJ', en: 'Djibouti', de: 'Dschibuti' },
  { code: 'DK', en: 'Denmark', de: 'Dänemark' },
  { code: 'DM', en: 'Dominica', de: 'Dominica' },
  { code: 'DO', en: 'Dominican Republic', de: 'Dominikanische Republik' },
  { code: 'DZ', en: 'Algeria', de: 'Algerien' },
  { code: 'EC', en: 'Ecuador', de: 'Ecuador' },
  { code: 'EE', en: 'Estonia', de: 'Estland' },
  { code: 'EG', en: 'Egypt', de: 'Ägypten' },
  { code: 'ER', en: 'Eritrea', de: 'Eritrea' },
  { code: 'ES', en: 'Spain', de: 'Spanien' },
  { code: 'ET', en: 'Ethiopia', de: 'Äthiopien' },
  { code: 'FI', en: 'Finland', de: 'Finnland' },
  { code: 'FJ', en: 'Fiji', de: 'Fidschi' },
  { code: 'FM', en: 'Micronesia, Federated States of', de: 'Mikronesien' },
  { code: 'FR', en: 'France', de: 'Frankreich' },
  { code: 'GA', en: 'Gabon', de: 'Gabun' },
  { code: 'GB', en: 'United Kingdom of Great Britain and Northern Ireland', de: 'Vereinigtes Königreich' },
  { code: 'GD', en: 'Grenada', de: 'Grenada' },
  { code: 'GE', en: 'Georgia', de: 'Georgien' },
  { code: 'GH', en: 'Ghana', de: 'Ghana' },
  { code: 'GM', en: 'Gambia', de: 'Gambia' },
  { code: 'GN', en: 'Guinea', de: 'Guinea' },
  { code: 'GQ', en: 'Equatorial Guinea', de: 'Äquatorialguinea' },
  { code: 'GR', en: 'Greece', de: 'Griechenland' },
  { code: 'GT', en: 'Guatemala', de: 'Guatemala' },
  { code: 'GW', en: 'Guinea-Bissau', de: 'Guinea-Bissau' },
  { code: 'GY', en: 'Guyana', de: 'Guyana' },
  { code: 'HN', en: 'Honduras', de: 'Honduras' },
  { code: 'HR', en: 'Croatia', de: 'Kroatien' },
  { code: 'HT', en: 'Haiti', de: 'Haiti' },
  { code: 'HU', en: 'Hungary', de: 'Ungarn' },
  { code: 'ID', en: 'Indonesia', de: 'Indonesien' },
  { code: 'IE', en: 'Ireland', de: 'Irland' },
  { code: 'IL', en: 'Israel', de: 'Israel' },
  { code: 'IN', en: 'India', de: 'Indien' },
  { code: 'IQ', en: 'Iraq', de: 'Irak' },
  { code: 'IR', en: 'Iran, Islamic Republic of', de: 'Iran' },
  { code: 'IS', en: 'Iceland', de: 'Island' },
  { code: 'IT', en: 'Italy', de: 'Italien' },
  { code: 'JM', en: 'Jamaica', de: 'Jamaika' },
  { code: 'JO', en: 'Jordan', de: 'Jordanien' },
  { code: 'JP', en: 'Japan', de: 'Japan' },
  { code: 'KE', en: 'Kenya', de: 'Kenia' },
  { code: 'KG', en: 'Kyrgyzstan', de: 'Kirgisistan' },
  { code: 'KH', en: 'Cambodia', de: 'Kambodscha' },
  { code: 'KI', en: 'Kiribati', de: 'Kiribati' },
  { code: 'KM', en: 'Comoros', de: 'Komoren' },
  { code: 'KN', en: 'Saint Kitts and Nevis', de: 'St. Kitts und Nevis' },
  { code: 'KP', en: 'Korea, Democratic People\'s Republic of', de: 'Korea, Nord (Nordkorea)' },
  { code: 'KR', en: 'Korea, Republic of', de: 'Korea, Süd (Südkorea)' },
  { code: 'KW', en: 'Kuwait', de: 'Kuwait' },
  { code: 'KZ', en: 'Kazakhstan', de: 'Kasachstan' },
  { code: 'LA', en: 'Lao People\'s Democratic Republic', de: 'Laos' },
  { code: 'LB', en: 'Lebanon', de: 'Libanon' },
  { code: 'LC', en: 'Saint Lucia', de: 'St. Lucia' },
  { code: 'LI', en: 'Liechtenstein', de: 'Liechtenstein' },
  { code: 'LK', en: 'Sri Lanka', de: 'Sri Lanka' },
  { code: 'LR', en: 'Liberia', de: 'Liberia' },
  { code: 'LS', en: 'Lesotho', de: 'Lesotho' },
  { code: 'LT', en: 'Lithuania', de: 'Litauen' },
  { code: 'LU', en: 'Luxembourg', de: 'Luxemburg' },
  { code: 'LV', en: 'Latvia', de: 'Lettland' },
  { code: 'LY', en: 'Libya', de: 'Libyen' },
  { code: 'MA', en: 'Morocco', de: 'Marokko' },
  { code: 'MC', en: 'Monaco', de: 'Monaco' },
  { code: 'MD', en: 'Moldova, Republic of', de: 'Moldau' },
  { code: 'ME', en: 'Montenegro', de: 'Montenegro' },
  { code: 'MG', en: 'Madagascar', de: 'Madagaskar' },
  { code: 'MH', en: 'Marshall Islands', de: 'Marshallinseln' },
  { code: 'MK', en: 'North Macedonia', de: 'Nordmazedonien' },
  { code: 'ML', en: 'Mali', de: 'Mali' },
  { code: 'MM', en: 'Myanmar', de: 'Myanmar' },
  { code: 'MN', en: 'Mongolia', de: 'Mongolei' },
  { code: 'MR', en: 'Mauritania', de: 'Mauretanien' },
  { code: 'MT', en: 'Malta', de: 'Malta' },
  { code: 'MU', en: 'Mauritius', de: 'Mauritius' },
  { code: 'MV', en: 'Maldives', de: 'Malediven' },
  { code: 'MW', en: 'Malawi', de: 'Malawi' },
  { code: 'MX', en: 'Mexico', de: 'Mexiko' },
  { code: 'MY', en: 'Malaysia', de: 'Malaysia' },
  { code: 'MZ', en: 'Mozambique', de: 'Mosambik' },
  { code: 'NA', en: 'Namibia', de: 'Namibia' },
  { code: 'NE', en: 'Niger', de: 'Niger' },
  { code: 'NG', en: 'Nigeria', de: 'Nigeria' },
  { code: 'NI', en: 'Nicaragua', de: 'Nicaragua' },
  { code: 'NL', en: 'Netherlands', de: 'Niederlande' },
  { code: 'NO', en: 'Norway', de: 'Norwegen' },
  { code: 'NP', en: 'Nepal', de: 'Nepal' },
  { code: 'NR', en: 'Nauru', de: 'Nauru' },
  { code: 'NZ', en: 'New Zealand', de: 'Neuseeland' },
  { code: 'OM', en: 'Oman', de: 'Oman' },
  { code: 'PA', en: 'Panama', de: 'Panama' },
  { code: 'PE', en: 'Peru', de: 'Peru' },
  { code: 'PG', en: 'Papua New Guinea', de: 'Papua-Neuguinea' },
  { code: 'PH', en: 'Philippines', de: 'Philippinen' },
  { code: 'PK', en: 'Pakistan', de: 'Pakistan' },
  { code: 'PL', en: 'Poland', de: 'Polen' },
  { code: 'PT', en: 'Portugal', de: 'Portugal' },
  { code: 'PW', en: 'Palau', de: 'Palau' },
  { code: 'PY', en: 'Paraguay', de: 'Paraguay' },
  { code: 'QA', en: 'Qatar', de: 'Katar' },
  { code: 'RO', en: 'Romania', de: 'Rumänien' },
  { code: 'RS', en: 'Serbia', de: 'Serbien' },
  { code: 'RU', en: 'Russian Federation', de: 'Russland' },
  { code: 'RW', en: 'Rwanda', de: 'Ruanda' },
  { code: 'SA', en: 'Saudi Arabia', de: 'Saudi-Arabien' },
  { code: 'SB', en: 'Solomon Islands', de: 'Salomonen' },
  { code: 'SC', en: 'Seychelles', de: 'Seychellen' },
  { code: 'SD', en: 'Sudan', de: 'Sudan' },
  { code: 'SE', en: 'Sweden', de: 'Schweden' },
  { code: 'SG', en: 'Singapore', de: 'Singapur' },
  { code: 'SI', en: 'Slovenia', de: 'Slowenien' },
  { code: 'SK', en: 'Slovakia', de: 'Slowakei' },
  { code: 'SL', en: 'Sierra Leone', de: 'Sierra Leone' },
  { code: 'SM', en: 'San Marino', de: 'San Marino' },
  { code: 'SN', en: 'Senegal', de: 'Senegal' },
  { code: 'SO', en: 'Somalia', de: 'Somalia' },
  { code: 'SR', en: 'Suriname', de: 'Suriname' },
  { code: 'SS', en: 'South Sudan', de: 'Südsudan' },
  { code: 'ST', en: 'Sao Tome and Principe', de: 'São Tomé und Príncipe' },
  { code: 'SV', en: 'El Salvador', de: 'El Salvador' },
  { code: 'SY', en: 'Syrian Arab Republic', de: 'Syrien' },
  { code: 'SZ', en: 'Eswatini', de: 'Eswatini' },
  { code: 'TD', en: 'Chad', de: 'Tschad' },
  { code: 'TG', en: 'Togo', de: 'Togo' },
  { code: 'TH', en: 'Thailand', de: 'Thailand' },
  { code: 'TJ', en: 'Tajikistan', de: 'Tadschikistan' },
  { code: 'TL', en: 'Timor-Leste', de: 'Osttimor' },
  { code: 'TM', en: 'Turkmenistan', de: 'Turkmenistan' },
  { code: 'TN', en: 'Tunisia', de: 'Tunesien' },
  { code: 'TO', en: 'Tonga', de: 'Tonga' },
  { code: 'TR', en: 'Türkiye', de: 'Türkei' },
  { code: 'TT', en: 'Trinidad and Tobago', de: 'Trinidad und Tobago' },
  { code: 'TV', en: 'Tuvalu', de: 'Tuvalu' },
  { code: 'TZ', en: 'Tanzania, United Republic of', de: 'Tansania' },
  { code: 'UA', en: 'Ukraine', de: 'Ukraine' },
  { code: 'UG', en: 'Uganda', de: 'Uganda' },
  { code: 'US', en: 'United States of America', de: 'Vereinigte Staaten' },
  { code: 'UY', en: 'Uruguay', de: 'Uruguay' },
  { code: 'UZ', en: 'Uzbekistan', de: 'Usbekistan' },
  { code: 'VC', en: 'Saint Vincent and the Grenadines', de: 'St. Vincent und die Grenadinen' },
  { code: 'VE', en: 'Venezuela, Bolivarian Republic of', de: 'Venezuela' },
  { code: 'VN', en: 'Viet Nam', de: 'Vietnam' },
  { code: 'VU', en: 'Vanuatu', de: 'Vanuatu' },
  { code: 'WS', en: 'Samoa', de: 'Samoa' },
  { code: 'YE', en: 'Yemen', de: 'Jemen' },
  { code: 'ZA', en: 'South Africa', de: 'Südafrika' },
  { code: 'ZM', en: 'Zambia', de: 'Sambia' },
  { code: 'ZW', en: 'Zimbabwe', de: 'Simbabwe' },
  { code: 'TW', en: 'Taiwan', de: 'Taiwan' },
  { code: 'PS', en: 'Palestine, State of', de: 'Palästina' },
  { code: 'VA', en: 'Holy See', de: 'Vatikanstadt' },
  { code: 'XK', en: 'Kosovo', de: 'Kosovo' },
];

const byCode = new Map(COUNTRIES.map((c) => [c.code, c]));

export function isCountryCode(value: unknown): value is string {
  return typeof value === 'string' && byCode.has(value.toUpperCase());
}

export function normalizeCountryCode(value: string): string | null {
  const code = value.trim().toUpperCase();
  return byCode.has(code) ? code : null;
}

export function countryLabel(code: string, locale: 'en' | 'de'): string {
  const c = byCode.get(code.toUpperCase());
  if (!c) return code;
  return locale === 'de' ? c.de : c.en;
}
