export const GUEST_ERROR = {
  NICKNAME_TOO_SHORT: "NICKNAME_TOO_SHORT",
  SEX_REQUIRED: "SEX_REQUIRED",
  LOOKING_FOR_REQUIRED: "LOOKING_FOR_REQUIRED",
  NICKNAME_BANNED: "NICKNAME_BANNED",
  SCOPE_REQUIRED: "SCOPE_REQUIRED",
} as const;

export type GuestErrorCode = (typeof GUEST_ERROR)[keyof typeof GUEST_ERROR];
